### PR TITLE
Fix image optimizer on Windows

### LINKED ISSUE #638: Image optimizer doesn't write to correct location on windows
It seems that #631 didn't actually fix it after all

### PR DESCRIPTION
**Pull request by elarb**
Changes:
- Writes to correct locations
- Optimizes the banner now (couldn't process with 2000x500)
- Prints warning if an error occurred
- Copy images anyways if optimizing isn't possible

Tested on Windows and Linux

Fixes #638

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -32,37 +32,42 @@ const imageOptions = {
...
+  banner: '750x500,scale-down'
 };
 
 // Optimize images with ImageOptim
 // Run with `yarn run build optimize-images`
 const optimizeImages = () => new Promise((resolve, reject) => {
   glob('images/**/*.{jpg,png,svg}', (err, files) => {
     for (const file of files) {
-      const relativeFile = file.substring(file.indexOf(path.sep) + 1);
+      const relativeFile = file.substring(file.indexOf('/') + 1);
```
Comment (TimvdLippe) [inline gulpfile.js]: I thought this was the original issue on Windows? What is here the value of `file` on a Windows machine?

Comment (elarb) [reply gulpfile.js]: screenshot

Comment (TimvdLippe) [reply gulpfile.js]: Aaahhh... Glob normalizes it. I see.
